# Generated by Django 5.0.8 on 2024-08-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nhanes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rule",
            options={"verbose_name_plural": "Rules"},
        ),
        migrations.AlterModelOptions(
            name="variable",
            options={"verbose_name": "Variable", "verbose_name_plural": "Variable"},
        ),
        migrations.RemoveField(
            model_name="rule",
            name="file_documentation",
        ),
    ]
