# Generated by Django 5.0.8 on 2024-08-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nhanes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="normalizationrule",
            name="created_at",
        ),
    ]
