# Generated by Django 5.0.8 on 2024-08-21 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nhanes", "0002_alter_rule_options_alter_variable_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rule",
            name="source",
        ),
        migrations.RemoveField(
            model_name="rule",
            name="target",
        ),
        migrations.CreateModel(
            name="RuleVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_source", models.BooleanField(default=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nhanes.dataset"
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nhanes.rule"
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nhanes.variable",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Rule Variables",
                "unique_together": {("rule", "variable", "dataset", "is_source")},
            },
        ),
    ]
