# Generated by Django 5.0.8 on 2024-08-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nhanes", "0002_remove_normalizationrule_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workprocessmasterdata",
            name="component_type",
            field=models.CharField(
                choices=[
                    ("rule", "Normalizations Rule"),
                    ("cycle", "Cycle"),
                    ("group", "Group"),
                    ("dataset", "Dataset"),
                    ("variable", "Variable"),
                    ("variable_cycle", "VariableCycle"),
                    ("field", "Field"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
