# Generated by Django 5.0.8 on 2024-08-23 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nhanes", "0003_remove_rule_source_remove_rule_target_rulevariable"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkProcessRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_synced_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("complete", "Complete"),
                            ("error", "Error"),
                            ("delete", "Delete"),
                            ("standby", "Stand By"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("execution_logs", models.TextField(blank=True, null=True)),
                ("execution_time", models.DurationField(blank=True, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                (
                    "rule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="nhanes.rule"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Work Process Rule",
            },
        ),
    ]
