# Generated by Django 5.0.8 on 2024-08-13 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("nhanes", "0003_alter_workprocessmasterdata_component_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logs",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="logs",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workprocessmasterdata",
            name="component_type",
            field=models.CharField(
                choices=[
                    ("NormalizationRule", "Normalizations Rule"),
                    ("Cycle", "Cycle"),
                    ("Group", "Group"),
                    ("Dataset", "Dataset"),
                    ("Variable", "Variable"),
                    ("DatasetCycle", "Dataset Cycle"),
                    ("VariableCycle", "Variable Cycle"),
                    ("Field", "Field"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
