# Generated by Django 5.0.8 on 2024-08-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nhanes", "0004_alter_logs_content_type_alter_logs_object_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workprocess",
            name="last_synced_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Update"),
        ),
    ]
