# Generated by Django 5.0.8 on 2024-08-16 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nhanes", "0006_systemconfig_config_check_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workprocess",
            options={"verbose_name_plural": "Work Process"},
        ),
    ]
