# Generated by Django 5.0.8 on 2024-08-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nhanes", "0007_alter_workprocess_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workprocessmasterdata",
            name="component_type",
            field=models.CharField(
                choices=[
                    ("NormalizationRule", "Normalizations Rule"),
                    ("Cycle", "Cycle"),
                    ("Group", "Group"),
                    ("Dataset", "Dataset"),
                    ("Variable", "Variable"),
                    ("DatasetCycle", "Dataset Cycle"),
                    ("VariableCycle", "Variable Cycle"),
                    ("Field", "Field"),
                    ("SystemConfig", "System Config"),
                    ("QueryColumns", "Query Columns"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
