# Generated by Django 5.0.8 on 2024-08-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nhanes", "0008_alter_workprocessmasterdata_component_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queryfilter",
            name="filter_name",
            field=models.CharField(
                choices=[
                    ("variable__variable", "Variable Code"),
                    ("variable__description", "Variable Name"),
                    ("cycle__cycle", "Cycle"),
                    ("dataset__group__group", "Group"),
                    ("dataset__dataset", "Dataset Code"),
                    ("dataset__description", "Dataset Name"),
                ],
                default="variable",
                max_length=30,
            ),
        ),
    ]
