# Generated by Django 5.0.6 on 2024-05-28 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhanes', '0013_alter_queryfilter_operator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ['cycle'], 'verbose_name': '01-Cycle', 'verbose_name_plural': '01-Cycles'},
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': '07-Data', 'verbose_name_plural': '07-Data'},
        ),
        migrations.AlterModelOptions(
            name='dataset',
            options={'verbose_name': '03-Dataset', 'verbose_name_plural': '03-Dataset'},
        ),
        migrations.AlterModelOptions(
            name='datasetcontrol',
            options={'verbose_name': '06-Donwload Control', 'verbose_name_plural': '06-Donwload Control'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': '04-Field', 'verbose_name_plural': '04-Field'},
        ),
        migrations.AlterModelOptions(
            name='fieldcycle',
            options={'verbose_name': '05-Field by Cycle', 'verbose_name_plural': '05-Field by Cycle'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '02-Group', 'verbose_name_plural': '02-Group'},
        ),
        migrations.AlterModelOptions(
            name='querystructure',
            options={'verbose_name': '08-Query Structure', 'verbose_name_plural': '08-Query Structure'},
        ),
    ]
