# Generated by Django 5.0.6 on 2024-05-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanes', '0014_alter_cycle_options_alter_data_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='data',
            unique_together={('cycle', 'dataset', 'field', 'sample')},
        ),
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['cycle', 'dataset', 'field', 'sample'], name='nhanes_data_cycle_i_19779b_idx'),
        ),
    ]
