# Generated by Django 5.0.6 on 2024-05-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanes', '0015_alter_data_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
