# Generated by Django 5.0.6 on 2024-05-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanes', '0018_alter_cycle_options_alter_data_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryfilter',
            name='filter_name',
            field=models.CharField(choices=[('field__field', 'Field Code'), ('field__description', 'Field Name'), ('field__internal_id', 'Field Internal Code'), ('cycle__cycle', 'Cycle'), ('dataset__group__group', 'Group'), ('dataset__dataset', 'Dataset Code'), ('dataset__description', 'Dataset Name')], default='field_id', max_length=30),
        ),
    ]
