# Generated by Django 5.0.6 on 2024-06-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanes', '0020_remove_data_nhanes_data_cycle_i_4b523f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='internal_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
