# Generated by Django 5.0.6 on 2024-06-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanes', '0021_field_internal_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryfilter',
            name='filter_name',
            field=models.CharField(choices=[('field__field', 'Field Code'), ('field__description', 'Field Name'), ('field__internal_id', 'Field Internal Code'), ('field__internal_group', 'Field Internal Group'), ('cycle__cycle', 'Cycle'), ('dataset__group__group', 'Group'), ('dataset__dataset', 'Dataset Code'), ('dataset__description', 'Dataset Name')], default='field_id', max_length=30),
        ),
    ]
