# Generated by Django 5.0.6 on 2024-06-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanes', '0022_alter_queryfilter_filter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryfilter',
            name='operator',
            field=models.CharField(choices=[('eq', 'Equal'), ('ne', 'Not Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('contains', 'Contains'), ('icontains', 'Contains (Case-Insensitive)'), ('exact', 'Exact'), ('iexact', 'Exact (Case-Insensitive)'), ('in', 'In'), ('startswith', 'Starts With'), ('istartswith', 'Starts With (Case-Insensitive)'), ('endswith', 'Ends With'), ('iendswith', 'Ends With (Case-Insensitive)'), ('isnull', 'Search For Null Values'), ('search', 'Search'), ('regex', 'Use Regular Expression'), ('iregex', 'Use Regular Expression (Case-Insensitive)'), ('file', 'Path to csv file with each value in a line')], default='eq', max_length=20),
        ),
    ]
